name: Deploy

on:
  workflow_call:

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: yarn install

    - name: Print dir
      run: ls

    - name: Build project
      run: yarn build


    - name: Print dir post build
      run: ls